### ISSUE TITLE
Flexibility of temporal dimension

### ISSUE THREAD

**Issue by terbed** [jackaduma/CycleGAN-VC3#3]
Hi,

In the corresponding article, the temporal frame length is 64 in the training. My question is that is it possible that after training we inputting different temporal lengths, or it is fixed?

Thanks,
Daniel

**Comment by terbed** [comment]
On the other hand, the model.py results in error:
@jackaduma 

```
Generator input:  torch.Size([1, 80, 64])
Generator forward input:  torch.Size([1, 80, 64])
Generator forward input:  torch.Size([1, 1, 80, 64])
Generator forward conv1:  torch.Size([1, 128, 80, 64])
Generator forward downsample1:  torch.Size([1, 256, 40, 32])
Generator forward downsample2:  torch.Size([1, 256, 20, 16])
Traceback (most recent call last):
  File "/home/terbed/PROJECTS/DYS/CycleGAN-VC3/src/model.py", line 441, in <module>
    output = generator(input)
  File "/home/terbed/anaconda3/envs/dys/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/terbed/PROJECTS/DYS/CycleGAN-VC3/src/model.py", line 290, in forward
    reshape2dto1d = downsample2.view(downsample2.size(0), 2304, 1, -1)
RuntimeError: shape '[1, 2304, 1, -1]' is invalid for input of size 81920
```
